### ISSUE TITLE
[Errno 2] No such file or directory: 'WisdomShell/CodeShell-7B-Chat-int4/pytorch_model.bin'

### ISSUE THREAD

**Issue by tt1998215** [WisdomShell/codeshell#16]
我修改了 webdemo.py
DEFAULT_CKPT_PATH = 'WisdomShell/CodeShell-7B-Chat-int4'

然后运行报错
    return model_class.from_pretrained(
  File "/root/.cache/huggingface/modules/transformers_modules/WisdomShell/CodeShell-7B-Chat-int4/10629399134587be6ea6d65f54c52c22a0c23c29/modeling_codeshell.py", line 1058, in from_pretrained
    state_dict = torch.load(os.path.join(pretrained_model_name_or_path, 'pytorch_model.bin'), map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'WisdomShell/CodeShell-7B-Chat-int4/pytorch_model.bin'

我把hugginface上的模型 下载了 去缓存
/root/.cache/huggingface/modules/transformers_modules/WisdomShell/CodeShell-7B-Chat-int4
/root/codeshell/demos/WisdomShell/CodeShell-7B-Chat-int4

在这两地方 都放了
还是找不到 
到底应该把模型放在哪呢

**Comment by tt1998215** [comment]
试了下DEFAULT_CKPT_PATH = 'WisdomShell/CodeShell-7B-Chat'
是没问题的

**Comment by Lowpower** [comment]
我也有这个问题

**Comment by Lowpower** [comment]
gguf: loading model part 'pytorch_model.bin'
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '../models/CodeShell-7B/pytorch_model.bin'

**Comment by Lowpower** [comment]
if num_parts == 0:
    part_names = iter(("pytorch_model.bin",))
else:
    part_names = (
        f"pytorch_model-{n:05}-of-{num_parts:05}.bin" for n in range(1, num_parts + 1)
    )
huggingface下载的文件里没有这个

**Comment by ruixie** [comment]
默认地址与您本地的配置有关，如果是手动下载的模型，建议将DEFAULT_CKPT_PATH改为绝对地址

**Comment by tt1998215** [comment]
> 默认地址与您本地的配置有关，如果是手动下载的模型，建议将DEFAULT_CKPT_PATH改为绝对地址

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
A new version of the following files was downloaded from https://huggingface.co/WisdomShell/CodeShell-7B-Chat-int4:
- configuration_codeshell.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading (…)odeling_codeshell.py: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48.2k/48.2k [00:00<00:00, 223kB/s]
A new version of the following files was downloaded from https://huggingface.co/WisdomShell/CodeShell-7B-Chat-int4:
- quantizer.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/WisdomShell/CodeShell-7B-Chat-int4:
- modeling_codeshell.py
- quantizer.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Traceback (most recent call last):
  File "/root/codeshell/demos/web_demo.py", line 208, in <module>
    main()
  File "/root/codeshell/demos/web_demo.py", line 202, in main
    model, tokenizer, config = _load_model_tokenizer(args)
  File "/root/codeshell/demos/web_demo.py", line 63, in _load_model_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
    return model_class.from_pretrained(
  File "/root/.cache/huggingface/modules/transformers_modules/WisdomShell/CodeShell-7B-Chat-int4/58af5264430bed579746af4e39f0ba1c73a7251e/modeling_codeshell.py", line 1044, in from_pretrained
    state_dict = torch.load(os.path.join(pretrained_model_name_or_path, 'pytorch_model.bin'), map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'WisdomShell/CodeShell-7B-Chat-int4/pytorch_model.bin'

好像是在服务器上找到了两个版本 然后 也不知道 该输入个啥 最后啥也没下载
