### ISSUE TITLE
demos/web_demo.py可以运行，但是报错“NameError: name 'device' is not defined”

### ISSUE THREAD

**Issue by whtwhtw** [WisdomShell/codeshell#20]
demos/web_demo.py运行后：
Running on local URL:  http://127.0.0.1:8000

To create a public link, set `share=True` in `launch()`.
表明已经正常运行，当输入文字提交后报错：
User: 用python写一个web页面
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\blocks.py", line 1121, in call_function
    prediction = await utils.async_iteration(iterator)
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "web_demo.py", line 149, in predict
    input_ids = tokenizer(_query, return_tensors="pt").input_ids.to(device)
NameError: name 'device' is not defined

**Comment by whtwhtw** [comment]
当我强行把input_ids = tokenizer(_query, return_tensors="pt").input_ids.to(device)
改为input_ids = tokenizer(_query, return_tensors="pt").input_ids.to(‘cuda’)后依然报错：
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\blocks.py", line 1121, in call_function
    prediction = await utils.async_iteration(iterator)
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "d:\ProgramData\Anaconda3\envs\torch\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "web_demo.py", line 170, in predict
    full_response = _parse_text(response)
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by ruixie** [comment]
感谢您的关注，代码已更新，请更新至最新代码再次尝试。
