### ISSUE TITLE
自己量化操作时报错

### ISSUE THREAD

**Issue by bopresslte** [WisdomShell/codeshell#38]
Loading model file ..\models\CodeShell-7B-Chat\pytorch_model-00001-of-00002.bin
Loading model file ..\models\CodeShell-7B-Chat\pytorch_model-00001-of-00002.bin
Loading model file ..\models\CodeShell-7B-Chat\pytorch_model-00002-of-00002.bin
Traceback (most recent call last):
  File "D:\AutoAI\llama_cpp_for_codeshell-master\convert.py", line 1193, in <module>
    main()
  File "D:\AutoAI\llama_cpp_for_codeshell-master\convert.py", line 1134, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AutoAI\llama_cpp_for_codeshell-master\convert.py", line 1056, in load_some_model
    model_plus = merge_multifile_models(models_plus)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AutoAI\llama_cpp_for_codeshell-master\convert.py", line 589, in merge_multifile_models        
    model = merge_sharded([mp.model for mp in models_plus])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AutoAI\llama_cpp_for_codeshell-master\convert.py", line 568, in merge_sharded
    return {name: convert(name) for name in names}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AutoAI\llama_cpp_for_codeshell-master\convert.py", line 568, in <dictcomp>
    return {name: convert(name) for name in names}
                  ^^^^^^^^^^^^^
  File "D:\AutoAI\llama_cpp_for_codeshell-master\convert.py", line 543, in convert
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AutoAI\llama_cpp_for_codeshell-master\convert.py", line 543, in <listcomp>
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
                                      ~~~~~^^^^^^
KeyError: 'transformer.wte.weight'
PS D:\AutoAI\llama_cpp_for_codeshell-master> python .\convert.py ..\models\CodeShell-7B-Chat\

**Comment by chiranko** [comment]
You may consider using our provided script "convert-codeshell-hf-to-gguf.py" for the conversion.
