### ISSUE TITLE
评估脚本无法运行，我尝试安装lm_eval==0.2.0版本(以下报错是0.3.0版本)，但datasets包只能是1.15版本的，不满足bigcode-evaluation-harness项目的要求

### ISSUE THREAD

**Issue by Qiang-HU** [WisdomShell/codeshell#39]
py310) root@gpu-8-36:/Code_project/codeshell/evaluation# ./run_eval.sh local_gen /Code_project/model/CodeShell-7B-Chat/ ./output
Traceback (most recent call last):
  File "/Code_project/codeshell/evaluation/eval.py", line 25, in <module>
    from lm_eval.arguments import EvalArguments
ModuleNotFoundError: No module named 'lm_eval.arguments'
Traceback (most recent call last):
  File "/Code_project/codeshell/evaluation/eval.py", line 25, in <module>
    from lm_eval.arguments import EvalArguments
ModuleNotFoundError: No module named 'lm_eval.arguments'
Traceback (most recent call last):
  File "/Code_project/codeshell/evaluation/eval.py", line 25, in <module>
    from lm_eval.arguments import EvalArguments
ModuleNotFoundError: No module named 'lm_eval.arguments'
Traceback (most recent call last):
  File "/Code_project/codeshell/evaluation/eval.py", line 25, in <module>
    from lm_eval.arguments import EvalArguments
ModuleNotFoundError: No module named 'lm_eval.arguments'
Traceback (most recent call last):
  File "/Code_project/codeshell/evaluation/eval.py", line 25, in <module>
    from lm_eval.arguments import EvalArguments
ModuleNotFoundError: No module named 'lm_eval.arguments'
Traceback (most recent call last):
  File "/Code_project/codeshell/evaluation/eval.py", line 25, in <module>
    from lm_eval.arguments import EvalArguments
ModuleNotFoundError: No module named 'lm_eval.arguments'
Traceback (most recent call last):
  File "/Code_project/codeshell/evaluation/eval.py", line 25, in <module>
    from lm_eval.arguments import EvalArguments
ModuleNotFoundError: No module named 'lm_eval.arguments'
Traceback (most recent call last):
  File "/Code_project/codeshell/evaluation/eval.py", line 25, in <module>
    from lm_eval.arguments import EvalArguments
ModuleNotFoundError: No module named 'lm_eval.arguments'
[2023-10-26 17:38:03,781] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 26835) of binary: /root/anaconda3/envs/py310/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/py310/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by ZZR0** [comment]
您好，非常感谢您对CodeShell项目的支持，我们的评估脚本基于bigcode-evaluation-harness项目进行开发，对于特定的环境问题，建议您可以参照bigcode-evaluation-harness项目的文档进行解决。
